### ISSUE TITLE
Is there a way to get total number of query results

### ISSUE THREAD

**Issue by pratapan9** [willfaught/gockle#6]
gocql API gives an option to get total number of query results through iterator.NumRows(). Is there a way to get that through gockle API on iterator?

**Comment by willfaught** [comment]
Hey @pratapan9, I just stumbled on this issue. I'm sorry that I missed it. Not sure how that happened.

I glanced through the doc quickly and didn't see anything. It's been a couple years since I touched or used the code, so I don't remember if/why Iterator doesn't have it. Perhaps I mistakenly missed it. Sorry about that.

Please feel free to fork this under the license. I'm sure it's straightforward to add such a method yourself.
